# first, install Cypress, then run all tests (in parallel)
stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
install:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: build

  script:
    - npm ci
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify

# two jobs that run after "install" job finishes
# NPM dependencies and Cypress binary should be already installed
cypress-e2e:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: test
  before_script:
    - apt-get install -y zip
  script:
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests in parallel
    - npx cypress run --browser chrome
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./myReport
  after_script:
    - zip -r ./myReport/screenshots.zip ./myReport/screenshots
    - curl -X POST
      --header "Content-Type:multipart/form-data"
      -H "x-api-key:${CALLIOPE_API_KEY}"
      -F "file[]=@myReport/myTestProfile.json"
      -F "attachment[]=@myReport/myTestProfile.html"
      -F "attachment[]=@myReport/screenshots.zip"
      "https://app.calliope.pro/api/v2/profile/"${CALLIOPE_PROFILE_ID}"/import/?os=RSpec&platform=$CI_COMMIT_REF_SLUG&build=$REVISION&formatter=mochawesome"

api:e2e:
  image:
    name: postman/newman
    entrypoint: [""]
  stage: test
  before_script:
    - apk add zip unzip curl
  script:
    - newman run petstore.postman_collection.json -e peststore_swagger.postman_environment.json -r cli,json
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - newman_result.zip
  after_script:
    - cd newman; zip -r ../newman_result.zip *.json; cd ..
    - curl -X POST -H "x-api-key:${CALLIOPE_API_KEY}"
      -F file[]=@newman_result.zip
      "https://app.calliope.pro/api/v2/profile/"${CALLIOPE_PROFILE_ID}"/import" -k